# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/proAceBD/proAceBD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proAceBD || ORIG_REF_NAME==proAceBD} -quiet] -quiet

# IP: bd/proAceBD/ip/proAceBD_proAceIP_0_0/proAceBD_proAceIP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proAceBD_proAceIP_0_0 || ORIG_REF_NAME==proAceBD_proAceIP_0_0} -quiet] -quiet

# IP: bd/proAceBD/ip/proAceBD_processing_system7_0_0/proAceBD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proAceBD_processing_system7_0_0 || ORIG_REF_NAME==proAceBD_processing_system7_0_0} -quiet] -quiet

# IP: bd/proAceBD/ip/proAceBD_rst_ps7_0_100M_0/proAceBD_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proAceBD_rst_ps7_0_100M_0 || ORIG_REF_NAME==proAceBD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/proAceBD/ip/proAceBD_ps7_0_axi_periph_0/proAceBD_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proAceBD_ps7_0_axi_periph_0 || ORIG_REF_NAME==proAceBD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/proAceBD/ip/proAceBD_auto_pc_0/proAceBD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==proAceBD_auto_pc_0 || ORIG_REF_NAME==proAceBD_auto_pc_0} -quiet] -quiet

# XDC: w:/archives/PYNQ/proAcePL/proAcePL.gen/sources_1/bd/proAceBD/proAceBD_ooc.xdc
